# Configurations
title:            Robert Mařík Website
longtitle:        Robert Mařík Website
author:           Robert Mařík
email:            robert.marik.cz@gmail.com
description: >
  Webpages of a mathematician.

version:          1.0
gitbook_version:  3.2.3

url:              'https://robert-marik.github.io'
rss:              RSS

# bootstrap: use the remote theme for the site itself
# remote_theme: robert-marik

toc:
  enabled: true
  h_min: 1
  h_max: 2

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     ./assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..2
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           false

syntax_highlighter_style: colorful

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:  /:categories/:title

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
future: true

collections:
  pages:
    output: true
    title: Hlavní součásti
  pages-articles-mat:
    output: true
    title: Podpora výuky matematiky
  pages-articles-obecne:
    output: true
    title: Podpora výuky obecně
  pages-it:
    output: true
    title: Podpora využití počítačů
